controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint